- src/bindings/Main.cpp
See https://github.com/altmp/v8-helpers/pull/6
> Added DefaultDimension and GlobalDimension

- src/bindings/Main.cpp
> Change capitalization for dimension constants

- src/bindings/Main.cpp
See https://github.com/altmp/v8-helpers/pull/12
> Removed resourceName getter

- src/bindings/Player.cpp
See https://github.com/altmp/altv-issues/issues/364
> Prevent player.setDateTime from setting invalid values

- src/bindings/Main.cpp
See https://github.com/altmp/cpp-sdk/pull/15
> Add alt setPassword

- src/bindings/Player.cpp
See https://github.com/altmp/cpp-sdk/pull/16
> Add player isEntityInStreamRange

- src/bindings/Main.cpp
Related to https://github.com/altmp/v8-helpers/pull/25
> Remove hasResource

- src/events/Main.cpp
Adds back events that were accidentally removed in the transition to Node v14.
> Adds back missing events

- src/bindings/Player.cpp
> Add player.emit

- client/src/CV8Resource.cpp
- client/src/CV8ScriptRuntime.h
- client/src/bindings/HandlingData.cpp
- client/src/bindings/Main.cpp
- client/src/bindings/MapZoomData.cpp
- client/src/bindings/MemoryBuffer.cpp
- client/src/bindings/Player.cpp
- client/src/bindings/Profiler.cpp
- client/src/bindings/V8Natives.cpp
- client/src/bindings/WebSocketClient.cpp
- client/src/events/Entity.cpp
- client/src/events/Main.cpp
- client/src/events/Vehicle.cpp
- server/src/CNodeResourceImpl.cpp
- server/src/bindings/Player.cpp
- server/src/bindings/vehicle/Appearance.h
- server/src/events/Main.cpp
- server/src/events/Player.cpp
- server/src/events/Vehicle.cpp
- shared/V8Helpers.cpp
- shared/V8Helpers.h
- shared/V8ResourceImpl.cpp
- shared/V8ResourceImpl.h
- shared/bindings/File.cpp
- shared/bindings/RGBA.cpp
- shared/bindings/Vector2.cpp
- shared/bindings/Vector3.cpp
- shared/events/Main.cpp
> JS value helper

- shared/bindings/Vector2.cpp
- shared/bindings/Vector3.cpp
Allow for just 1 number to be passed to the Vector2 and Vector3 constructor
> Add constructor overload to Vector class

- client/src/bindings/Worker.cpp
- client/src/workers/CWorker.cpp
- client/src/workers/CWorker.h
- client/src/workers/Globals.cpp
- client/src/workers/Globals.h
See #71 
Types
```ts
class Worker {
static addSharedArrayBuffer(buffer: SharedArrayBuffer): number;
static removeSharedArrayBuffer(index: number): void;
}
interface AltWorker {
getSharedArrayBuffer(index: number): SharedArrayBuffer;
}
```
> Add shared array buffer sharing support to workers

- client/src/workers/CWorker.cpp
- shared/V8FastFunction.cpp
- shared/V8FastFunction.h
- shared/helpers/Bindings.h
Add wrapper for registering functions using Fast C API
> Fast C API

- shared/bindings/Utils.js
wip & open to discussions
This pull request adds:
client:
- requestAnimDict
- requestAnimSet
- requestClipSet
- requestCutscene
> Add javascript utils functions

- server/src/bindings/Player.cpp
Adds `player.spawn(model: string | number, pos: alt.IVector3)`
> server: Add player.spawn(model, pos) overload

- shared/bindings/Utils.js
Added args type validation
Added more args to drawText3d
> Improve draw text utils

- .vscode/settings.json
- shared/bindings/Utils.js
```js
import alt from 'alt-shared'
const command = new alt.Utils.ConsoleCommand("example", (...args) => {
alt.log(args)
command.destroy()
})
```
> Add alt.Utils.ConsoleCommand

- shared/bindings/Resource.cpp
> shared: Fix resource valid getter

- shared/bindings/BaseObject.cpp
types: https://github.com/altmp/altv-types/pull/245
> shared: add baseobject id getter

- shared/bindings/BindingsMain.cpp
types: https://github.com/altmp/altv-types/pull/246
> shared: getMetaKeys & getSyncedMetaKeys

- client/src/bindings/NetworkObject.cpp
Adds toString, getByID, getByScriptID and getByRemoteID to NetworkObject.
I made it because i need to access getByRemoteID on the client.
> Client: Add NetworkObject static methods

- shared/helpers/Serialization.cpp
Fixes (de)serialization of IEntity in raw emits and extends it to all baseobjects.
DOES NOT fix issue 277 (I don't know how to fix it)
> Fix baseobject (de)serialization in raw emits

- client/src/bindings/AudioFilter.cpp
V8 argument size in the chorus effect and echo4 effect was wrong.
> client: fix v8 argument size effects
